### ISSUE TITLE
Landing page issues

### ISSUE THREAD

**Issue by jmignault** [natehill/dcmny-wireframes#8]
The interface on the landing page is somewhat inconsistent. There are 3 sections: Search, Recent activity, and Actions. 

Recent Activity and Actions have header labels. Search does not.

If the blue area in Actions represents a menu of sorts, then Actions should be a header label above and outside the blue area.

Perhaps each section should be indented ever so slightly. Maybe there should be a "Search" heading above the search box.

It might also be useful to adopt a case convention for labels. At the moment there is a mix of lower and sentence case.

**Comment by natehill** [comment]
got it @jmignault i will look to make this consistent thank you

**Comment by natehill** [comment]
i think i took care of all of this. no doubt some of it will come up again though.
